find_package(Vulkan REQUIRED FATAL_ERROR)

set(INCLUDED_INCLUDE_DIRECTORIES ${INCLUDED_INCLUDE_DIRECTORIES}
    ${Vulkan_INCLUDE_DIRS}
    ${SRC_DIR}/renderer
)

message ("Vulkan_INCLUDE_DIRS: '${Vulkan_INCLUDE_DIRS}'")

set(INCLUDED_DEPENDENCIES ${INCLUDED_DEPENDENCIES}
    er_vulkan
)

set(INCLUDED_LINK_LIBRARIES ${INCLUDED_LINK_LIBRARIES}
    er_vulkan
)